from __future__ import annotations

ADMIN_PANEL_HTML = r"""<!doctype html>
<html lang="fr">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Barka Tunnel Admin</title>
<style>
:root{--blue:#126ee8;--blue-2:#0b60d1;--navy:#0f172a;--navy-2:#182235;--muted:#667085;--line:#e2e8f0;--bg:#f4f7fb;--surface:#fff;--ok:#16a34a;--bad:#dc2626;--warn:#d97706;--shadow:0 12px 35px rgba(15,23,42,.08)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font-family:Inter,system-ui,-apple-system,Segoe UI,sans-serif;background:var(--bg);color:var(--navy)}button,input,select,textarea{font:inherit}
.hidden{display:none!important}.mobile-only{display:none}.desktop-only{display:inline-flex}
.login-page{min-height:100vh;display:grid;place-items:center;padding:24px;background:radial-gradient(circle at top right,#dbeafe 0,transparent 35%),linear-gradient(135deg,#f8fbff,#eef4ff)}
.login-card{width:min(460px,100%);background:#fff;border:1px solid var(--line);border-radius:28px;padding:28px;box-shadow:0 24px 70px rgba(15,23,42,.12)}.brand-lockup{display:flex;align-items:center;gap:13px;margin-bottom:24px}.brand-mark{width:48px;height:48px;border-radius:16px;display:grid;place-items:center;background:#fff;box-shadow:0 10px 24px rgba(18,110,232,.18);border:1px solid #dbeafe;overflow:hidden}.brand-mark svg{width:88%;height:88%;display:block}.brand-lockup h1{font-size:21px;margin:0}.brand-lockup p{margin:3px 0 0;color:var(--muted);font-size:13px}
.app-shell{min-height:100vh;display:grid;grid-template-columns:255px 1fr}.sidebar{position:sticky;top:0;height:100vh;background:linear-gradient(180deg,#0d1729,#111d31);color:#fff;padding:18px 14px;display:flex;flex-direction:column;z-index:20}.side-brand{display:flex;align-items:center;gap:11px;padding:8px 8px 20px;border-bottom:1px solid rgba(255,255,255,.08);margin-bottom:14px}.side-brand .brand-mark{width:40px;height:40px;border-radius:13px}.side-brand strong{display:block}.side-brand span{display:block;color:#9fb0c9;font-size:11px;margin-top:2px}.nav-label{color:#72839f;font-size:10px;font-weight:800;letter-spacing:.12em;padding:11px 10px 7px;text-transform:uppercase}.nav{display:grid;gap:5px}.nav button{width:100%;display:flex;align-items:center;gap:11px;border:0;background:transparent;color:#b9c5d7;padding:11px 12px;border-radius:12px;text-align:left;font-weight:700;cursor:pointer}.nav button:hover{background:rgba(255,255,255,.07);color:#fff}.nav button.active{background:linear-gradient(90deg,rgba(18,110,232,.28),rgba(18,110,232,.12));color:#fff;box-shadow:inset 3px 0 0 #4da0ff}.nav-icon{width:24px;text-align:center;font-size:16px}.side-footer{margin-top:auto;padding:12px 8px;border-top:1px solid rgba(255,255,255,.08)}.side-footer .small{color:#7f91ac}
.main{min-width:0}.topbar{height:72px;position:sticky;top:0;z-index:15;background:rgba(244,247,251,.92);backdrop-filter:blur(16px);border-bottom:1px solid rgba(226,232,240,.85);display:flex;align-items:center;justify-content:space-between;padding:0 28px}.topbar h2{font-size:19px;margin:0}.topbar p{font-size:12px;color:var(--muted);margin:2px 0 0}.top-actions{display:flex;align-items:center;gap:8px}.content{padding:24px 28px 40px;max-width:1500px;margin:auto}.page{display:none}.page.active{display:block}.page-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;margin-bottom:18px}.page-head h1{font-size:25px;margin:0 0 5px}.page-head p{color:var(--muted);margin:0;font-size:13px}
.card{background:var(--surface);border:1px solid var(--line);border-radius:20px;padding:20px;margin-bottom:18px;box-shadow:var(--shadow)}.title{font-weight:850;font-size:18px;margin-bottom:12px;color:#0b60d1}.section-note{color:var(--muted);font-size:12px;margin-top:-5px;margin-bottom:14px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.stat{border:1px solid var(--line);border-radius:17px;padding:16px;background:linear-gradient(180deg,#fff,#fbfdff)}.stat b{display:block;font-size:28px;letter-spacing:-.03em}.stat span{font-size:12px;color:var(--muted)}
label{display:block;font-size:12px;font-weight:750;margin:10px 0 6px;color:#344054}input,select,textarea{width:100%;border:1px solid #cfd7e6;border-radius:12px;padding:11px 12px;background:#fff;color:#111827;outline:none;transition:.18s}input:focus,select:focus,textarea:focus{border-color:#69a7f5;box-shadow:0 0 0 4px rgba(18,110,232,.09)}textarea{min-height:135px;font-family:ui-monospace,SFMono-Regular,monospace;font-size:12px;resize:vertical}button{border:0;border-radius:12px;padding:11px 14px;background:var(--blue);color:#fff;font-weight:800;font-size:13px;cursor:pointer;transition:.18s}button:hover{filter:brightness(.98);transform:translateY(-1px)}button.secondary{background:#eef4ff;color:#0b60d1}button.ghost{background:#fff;color:#344054;border:1px solid var(--line)}button.danger{background:#fff1f2;color:#be123c;border:1px solid #fecdd3}.icon-btn{width:40px;height:40px;padding:0;display:grid;place-items:center}.row{display:flex;gap:10px;align-items:center}.row>*{flex:1}.status{font-size:13px;margin:10px 0;padding:11px 12px;border-radius:12px;background:#f2f4f7}.ok{color:var(--ok)}.bad{color:var(--bad)}.code{font-family:ui-monospace,monospace;font-weight:800;letter-spacing:.4px}.code-row{border-top:1px solid #eef1f6;padding:11px 0}.code-actions{display:flex;gap:7px;justify-content:flex-end;flex:0 0 auto}.code-actions button{flex:0 0 auto;padding:8px 10px}.small{font-size:11px;color:var(--muted)}.services{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.service{border:1px solid var(--line);border-radius:18px;padding:16px;background:#fff}.pill{font-size:10px;font-weight:850;background:#eef4ff;color:#0b60d1;border-radius:99px;padding:5px 8px;display:inline-block;white-space:nowrap}.switch{display:flex;align-items:center;gap:8px}.switch input{width:auto}.toolbar{display:flex;gap:8px;flex-wrap:wrap}.toolbar button{min-width:130px}.two-col{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(280px,.75fr);gap:18px}.filterbar{display:flex;gap:10px;align-items:center;margin:12px 0}.filterbar input{flex:1}.muted-box{background:#f8fafc;border:1px dashed #cbd5e1;border-radius:14px;padding:13px;color:var(--muted);font-size:12px}.quick-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.quick{border:1px solid var(--line);border-radius:16px;padding:15px;background:#fbfdff}.quick b{display:block;margin-bottom:4px}.quick span{font-size:12px;color:var(--muted)}
.overlay{display:none}.toast{position:fixed;right:20px;bottom:20px;z-index:50;background:#0f172a;color:#fff;padding:12px 15px;border-radius:12px;box-shadow:0 14px 40px rgba(15,23,42,.24);font-size:13px;opacity:0;pointer-events:none;transform:translateY(10px);transition:.22s}.toast.show{opacity:1;transform:none}
@media(max-width:1080px){.grid{grid-template-columns:repeat(2,1fr)}.services{grid-template-columns:1fr}.two-col{grid-template-columns:1fr}.quick-grid{grid-template-columns:1fr 1fr}}
@media(max-width:760px){.mobile-only{display:inline-flex}.desktop-only{display:none}.app-shell{display:block}.sidebar{position:fixed;left:-270px;width:255px;transition:.22s;box-shadow:18px 0 55px rgba(15,23,42,.28)}.app-shell.menu-open .sidebar{left:0}.overlay{display:block;position:fixed;inset:0;background:rgba(15,23,42,.42);z-index:19;opacity:0;pointer-events:none;transition:.22s}.app-shell.menu-open .overlay{opacity:1;pointer-events:auto}.topbar{height:64px;padding:0 14px}.topbar h2{font-size:17px}.content{padding:18px 14px 34px}.page-head{display:block}.page-head h1{font-size:22px}.grid{grid-template-columns:repeat(2,1fr)}.quick-grid{grid-template-columns:1fr}.row.mobile-stack{display:block}.filterbar{align-items:stretch;flex-direction:column}.stat{padding:14px}.stat b{font-size:24px}.card{padding:16px;border-radius:17px}.login-card{padding:22px;border-radius:22px}}
</style>
</head>
<body>
<div id="loginCard" class="login-page"><section class="login-card"><div class="brand-lockup"><div class="brand-mark"><svg viewBox="0 0 72 72" role="img" aria-label="Logo Barka Tunnel"><path d="M62 9C47 0 24 2 11 16C-1 29 1 50 15 62C29 74 51 70 63 56" fill="none" stroke="#126ee8" stroke-width="5" stroke-linecap="round"/><path d="M22 16V58M22 16H40C51 16 57 22 57 30C57 36 52 40 47 41C54 42 59 47 59 54C59 63 51 67 40 67H22" fill="none" stroke="#111827" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div><h1>Barka Tunnel Admin</h1><p>Console de gestion sécurisée</p></div></div><div class="title">Connexion administrateur</div><label>Mot de passe administrateur</label><input id="adminToken" type="password" autocomplete="current-password" placeholder="Mot de passe"><div style="height:10px"></div><button style="width:100%" onclick="login()">OUVRIR LE PANEL</button><div id="loginStatus" class="status">Le mot de passe reste seulement dans cette session du navigateur.</div></section></div>
<div id="app" class="app-shell hidden">
<div class="overlay" onclick="toggleMenu(false)"></div>
<aside class="sidebar"><div class="side-brand"><div class="brand-mark"><svg viewBox="0 0 72 72" role="img" aria-label="Logo Barka Tunnel"><path d="M62 9C47 0 24 2 11 16C-1 29 1 50 15 62C29 74 51 70 63 56" fill="none" stroke="#126ee8" stroke-width="5" stroke-linecap="round"/><path d="M22 16V58M22 16H40C51 16 57 22 57 30C57 36 52 40 47 41C54 42 59 47 59 54C59 63 51 67 40 67H22" fill="none" stroke="#111827" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div><strong>Barka Tunnel</strong><span>Administration</span></div></div><div class="nav-label">Navigation</div><nav class="nav"><button class="active" data-page="dashboard" onclick="showPage('dashboard',this)"><span class="nav-icon">⌂</span>Tableau de bord</button><button data-page="subscriptions" onclick="showPage('subscriptions',this)"><span class="nav-icon">¤</span>Abonnements</button><button data-page="codes" onclick="showPage('codes',this)"><span class="nav-icon">#</span>Codes Redeem</button><button data-page="vpn" onclick="showPage('vpn',this)"><span class="nav-icon">◈</span>Services VPN</button><button data-page="update" onclick="showPage('update',this)"><span class="nav-icon">↑</span>Mise à jour APK</button></nav><div class="nav-label">Outils</div><nav class="nav"><button onclick="window.open('/docs','_blank')"><span class="nav-icon">↗</span>API / Documentation</button><button onclick="refreshAll()"><span class="nav-icon">↻</span>Actualiser les données</button></nav><div class="side-footer"><button class="ghost" style="width:100%" onclick="logout()">Se déconnecter</button><div class="small" style="margin-top:10px;text-align:center">Barka Tunnel Admin</div></div></aside>
<main class="main"><header class="topbar"><div class="row" style="flex:0 1 auto"><button class="ghost icon-btn mobile-only" onclick="toggleMenu()">☰</button><div><h2 id="topTitle">Tableau de bord</h2><p id="topSubtitle">Vue générale de Barka Tunnel</p></div></div><div class="top-actions"><button class="ghost icon-btn" onclick="refreshAll()" title="Actualiser">↻</button><button class="secondary desktop-only" onclick="showPage('codes')">+ Nouveau code</button></div></header><div class="content">
<section class="page active" data-page="dashboard"><div class="page-head"><div><h1>Tableau de bord</h1><p>Suivi rapide de l'activité et accès aux fonctions essentielles.</p></div></div><section class="card"><div class="row"><div><div class="title" style="margin:0">Aperçu en temps réel</div><div class="small">Données fournies par le backend Barka Tunnel</div></div><button class="secondary" onclick="refreshAll()">ACTUALISER</button></div><div id="stats" class="grid" style="margin-top:14px"></div></section><section class="card"><div class="title">Accès rapides</div><div class="quick-grid"><div class="quick"><b>Codes Redeem</b><span>Générer et gérer les codes distribués manuellement.</span><div style="height:10px"></div><button class="secondary" onclick="showPage('codes')">GÉRER LES CODES</button></div><div class="quick"><b>Services VPN</b><span>Configurer Moov, Orange et Telecel.</span><div style="height:10px"></div><button class="secondary" onclick="showPage('vpn')">OUVRIR LES SERVICES</button></div><div class="quick"><b>Mise à jour APK</b><span>Publier une nouvelle version de l'application.</span><div style="height:10px"></div><button class="secondary" onclick="showPage('update')">GÉRER L'APK</button></div></div></section></section>
<section class="page" data-page="subscriptions"><div class="page-head"><div><h1>Abonnements</h1><p>Accès générés après un paiement utilisateur.</p></div></div><section class="card"><div class="row"><div><div class="title" style="margin:0">Abonnements payés</div><div class="small">Désactivez pour geler l'accès aux trois opérateurs. Supprimez pour retirer le temps restant lié à ce code.</div></div><button class="ghost" onclick="loadCodes()">RECHARGER</button></div><div class="filterbar"><input id="subscriptionSearch" placeholder="Rechercher un code, une offre ou un statut..." oninput="renderAccessLists()"><select id="subscriptionStatus" style="max-width:190px" onchange="renderAccessLists()"><option value="">Tous les statuts</option><option value="issued">Disponibles</option><option value="redeemed">Actifs / utilisés</option><option value="revoked">Désactivés</option></select></div><div id="subscriptions"></div></section></section>
<section class="page" data-page="codes"><div class="page-head"><div><h1>Codes Redeem</h1><p>Codes manuels que vous créez et distribuez.</p></div></div><div class="two-col"><section class="card"><div class="title">Générer des codes Redeem</div><div class="row mobile-stack"><div><label>Offre</label><select id="plan"><option value="24h">24 heures — 300 XOF</option><option value="1w">1 semaine — 800 XOF</option><option value="2w">2 semaines — 1 000 XOF</option><option value="1m">1 mois — 2 000 XOF</option></select></div><div><label>Quantité</label><input id="count" type="number" min="1" max="100" value="1"></div></div><div style="height:10px"></div><button onclick="generateCodes()">GÉNÉRER</button><div id="generated"></div></section><section class="card"><div class="title">Informations</div><div class="muted-box"><b>Codes Redeem :</b> vous pouvez les donner aux utilisateurs. Après activation, vous gardez la possibilité de désactiver l'accès ou de supprimer le code et son temps restant.</div></section></div><section class="card"><div class="row"><div><div class="title" style="margin:0">Codes Redeem</div><div class="small">Liste séparée des abonnements issus d'un paiement.</div></div><button class="ghost" onclick="loadCodes()">RECHARGER</button></div><div class="filterbar"><input id="codeSearch" placeholder="Rechercher un code, une offre ou un statut..." oninput="renderAccessLists()"><select id="codeStatus" style="max-width:190px" onchange="renderAccessLists()"><option value="">Tous les statuts</option><option value="issued">Disponibles</option><option value="redeemed">Actifs / utilisés</option><option value="revoked">Désactivés</option></select></div><div id="codes"></div></section></section>
<section class="page" data-page="vpn"><div class="page-head"><div><h1>Services VPN</h1><p>Profils dynamiques distribués à l'application selon l'opérateur.</p></div></div><section class="card"><div class="title">Profils opérateurs</div><div class="section-note">MOOV = SlowDNS • Orange = VLESS • Telecel = UDP. Le protocole de chaque opérateur reste verrouillé côté serveur.</div><div id="services" class="services"></div></section></section>
<section class="page" data-page="update"><div class="page-head"><div><h1>Mise à jour de l'application</h1><p>Publication et contrôle des versions APK distribuées aux utilisateurs.</p></div></div><section class="card"><div class="title">Paramètres de publication</div><div class="row"><label class="switch"><input id="updEnabled" type="checkbox"> Activer les mises à jour</label><label class="switch"><input id="updMandatory" type="checkbox"> Mise à jour obligatoire</label></div><div class="row mobile-stack"><div><label>Version code</label><input id="updCode" type="number" min="1"></div><div><label>Version affichée</label><input id="updName" placeholder="1.1.0"></div></div><label>Lien HTTPS de l'APK</label><input id="updUrl" placeholder="https://..."><label>Ou téléverser directement un APK</label><input id="apkFile" type="file" accept=".apk,application/vnd.android.package-archive"><div style="height:8px"></div><button class="secondary" onclick="uploadApk()">TÉLÉVERSER L'APK</button><label>Message affiché aux utilisateurs</label><textarea id="updMessage" style="min-height:100px"></textarea><div style="height:10px"></div><button onclick="saveUpdate()">ENREGISTRER LA MISE À JOUR</button><div id="updateStatus" class="status"></div></section></section>
</div></main></div><div id="toast" class="toast"></div>
<script>
let TOKEN=sessionStorage.getItem('barkaAdminToken')||'';
let latestCodes=[];
const pageMeta={dashboard:['Tableau de bord','Vue générale de Barka Tunnel'],subscriptions:['Abonnements','Paiements et accès utilisateurs'],codes:["Codes Redeem",'Création et distribution manuelle'],vpn:['Services VPN','Profils dynamiques des opérateurs'],update:["Mise à jour APK","Publication de l'application"]};
const $=id=>document.getElementById(id);
function toggleMenu(force){const app=$('app');if(!app)return;const next=typeof force==='boolean'?force:!app.classList.contains('menu-open');app.classList.toggle('menu-open',next)}
function showPage(name,btn){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===name));document.querySelectorAll('.nav button[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===name));const meta=pageMeta[name]||pageMeta.dashboard;$('topTitle').textContent=meta[0];$('topSubtitle').textContent=meta[1];toggleMenu(false);window.scrollTo({top:0,behavior:'smooth'})}
function toast(msg){const el=$('toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function api(path,opt={}){const headers={'Accept':'application/json','X-Admin-Token':TOKEN,...(opt.headers||{})};if(opt.body)headers['Content-Type']='application/json';const r=await fetch(path,{...opt,headers,cache:'no-store'});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.detail||('HTTP '+r.status));return data}
async function login(){TOKEN=$('adminToken').value.trim();if(!TOKEN)return;try{await api('/v1/admin/stats');sessionStorage.setItem('barkaAdminToken',TOKEN);$('loginCard').classList.add('hidden');$('app').classList.remove('hidden');await refreshAll()}catch(e){$('loginStatus').innerHTML='<span class="bad">'+esc(e.message)+'</span>';TOKEN=''}}
function logout(){sessionStorage.removeItem('barkaAdminToken');TOKEN='';location.reload()}
async function refreshAll(){try{await Promise.all([loadStats(),loadCodes(),loadServices(),loadUpdate()])}catch(e){if(String(e.message).includes('refusé'))logout();else alert(e.message)}}
async function loadStats(){const s=await api('/v1/admin/stats');const items=[['Appareils',s.devices],['Abonnements actifs',s.active_subscriptions],['Essais actifs',s.active_trials],['Codes disponibles',s.codes_issued],['Codes utilisés',s.codes_redeemed],['Paiements confirmés',s.payments_paid],['Paiements en attente',s.payments_pending],['Services actifs',s.vpn_services_enabled]];$('stats').innerHTML=items.map(x=>'<div class="stat"><b>'+esc(x[1])+'</b><span>'+esc(x[0])+'</span></div>').join('')}
async function generateCodes(){const d=await api('/v1/admin/codes',{method:'POST',body:JSON.stringify({plan_id:$('plan').value,count:Number($('count').value||1)})});$('generated').innerHTML='<div class="status ok">'+d.codes.map(c=>'<div class="code">'+esc(c)+' <button class="secondary" style="padding:6px" onclick="copyText(\''+c+'\')">COPIER</button></div>').join('')+'</div>';await loadCodes();await loadStats()}
async function copyText(t){await navigator.clipboard.writeText(t);toast('Code copié')}
async function loadCodes(){latestCodes=await api('/v1/admin/codes?limit=200');renderAccessLists()}
function formatDate(v){if(!v)return '—';const d=new Date(v);if(Number.isNaN(d.getTime()))return '—';return String(d.getUTCDate()).padStart(2,'0')+'-'+String(d.getUTCMonth()+1).padStart(2,'0')+'-'+d.getUTCFullYear()}
function statusLabel(v){return v==='issued'?'Disponible':v==='redeemed'?'Actif / utilisé':v==='revoked'?'Désactivé':v}
function actionButtons(c){if(c.status==='revoked')return '<button class="secondary" onclick="reactivateCode(\''+c.code+'\')">RÉACTIVER</button><button class="danger" onclick="deleteCode(\''+c.code+'\')">SUPPRIMER</button>';return '<button class="ghost" onclick="revokeCode(\''+c.code+'\')">DÉSACTIVER</button><button class="danger" onclick="deleteCode(\''+c.code+'\')">SUPPRIMER</button>'}
function renderCodeRows(list,emptyText){return list.length?list.map(c=>'<div class="code-row"><div class="row mobile-stack"><div><div class="code">'+esc(c.code)+'</div><div class="small">'+esc(c.plan_id)+' • '+esc(statusLabel(c.status))+'</div><div class="small">Créé : '+formatDate(c.created_at)+' • Expire : '+formatDate(c.expires_at)+'</div></div><div class="code-actions">'+actionButtons(c)+'</div></div></div>').join(''):'<div class="status">'+esc(emptyText)+'</div>'}
function renderAccessLists(){const cq=($('codeSearch')?.value||'').trim().toLowerCase();const cs=$('codeStatus')?.value||'';const sq=($('subscriptionSearch')?.value||'').trim().toLowerCase();const ss=$('subscriptionStatus')?.value||'';const matches=(c,q,st)=>(!st||c.status===st)&&(!q||[c.code,c.plan_id,c.status,c.redeemed_device_id].some(v=>String(v||'').toLowerCase().includes(q)));const manual=latestCodes.filter(c=>c.source_type==='MANUEL'&&matches(c,cq,cs));const paid=latestCodes.filter(c=>c.source_type==='PAIEMENT'&&matches(c,sq,ss));if($('codes'))$('codes').innerHTML=renderCodeRows(manual,'Aucun code Redeem correspondant.');if($('subscriptions'))$('subscriptions').innerHTML=renderCodeRows(paid,'Aucun abonnement correspondant.')}
async function revokeCode(code){if(!confirm('Désactiver cet accès ? L’utilisateur ne pourra plus se connecter à MOOV, Orange ni Telecel.'))return;const d=await api('/v1/admin/codes/revoke',{method:'POST',body:JSON.stringify({code})});alert(d.message);await loadCodes();await loadStats()}
async function reactivateCode(code){if(!confirm('Réactiver cet accès ?'))return;const d=await api('/v1/admin/codes/reactivate',{method:'POST',body:JSON.stringify({code})});alert(d.message);await loadCodes();await loadStats()}
async function deleteCode(code){if(!confirm('Supprimer cet accès ? Le temps restant provenant de ce code sera retiré.'))return;const d=await api('/v1/admin/codes/delete',{method:'POST',body:JSON.stringify({code})});alert(d.message);if(d.success){latestCodes=latestCodes.filter(c=>c.code!==code)}renderAccessLists();await loadStats()}
async function loadServices(){const list=await api('/v1/admin/vpn/profiles');$('services').innerHTML=list.map(p=>{const cfg=p.config||{};const slowMissing=p.protocol==='SLOWDNS'&&!(cfg.dns_public_key||cfg.dnstt_public_key||cfg.public_key||cfg.publicKey);const warning=slowMissing?'<div class="status bad"><b>Configuration incomplète :</b> ajoute la clé <code>dns_public_key</code> fournie par ton serveur SlowDNS.</div>':'';return '<div class="service" data-id="'+esc(p.network_id)+'"><div class="row"><b>'+esc(p.display_name)+'</b><span class="pill">'+esc(p.protocol)+'</span></div><label class="switch"><input class="enabled" type="checkbox" '+(p.enabled?'checked':'')+'> Service actif</label><label class="switch"><input class="maintenance" type="checkbox" '+(p.maintenance?'checked':'')+'> Maintenance</label><label>Priorité</label><input class="priority" type="number" min="1" max="1000" value="'+esc(p.priority)+'"><label>Configuration JSON</label><textarea class="config">'+esc(JSON.stringify(cfg,null,2))+'</textarea>'+warning+'<div class="small">Version serveur : '+esc(p.version)+' • '+esc(p.updated_at)+'</div><div style="height:9px"></div><button onclick="saveService(\''+p.network_id+'\',\''+p.display_name+'\',\''+p.protocol+'\')">ENREGISTRER</button></div>'}).join('')}
async function saveService(id,name,protocol){const el=document.querySelector('.service[data-id="'+id+'"]');let config={};try{config=JSON.parse(el.querySelector('.config').value||'{}')}catch{alert('JSON invalide');return}const enabled=el.querySelector('.enabled').checked;const maintenance=el.querySelector('.maintenance').checked;if(enabled&&protocol==='SLOWDNS'){const pub=config.dns_public_key||config.dnstt_public_key||config.public_key||config.publicKey;const ns=config.nameserver||config.name_server||config.ns;if(!pub||!ns){alert('SlowDNS incomplet : ajoute le Name Server et la DNS Public Key avant activation.');return}}const body={network_id:id,display_name:name,protocol,enabled,maintenance,priority:Number(el.querySelector('.priority').value||100),config};await api('/v1/admin/vpn/profiles',{method:'POST',body:JSON.stringify(body)});await loadServices();await loadStats();alert(maintenance?'Maintenance enregistrée pour ce réseau.':'Service enregistré et nouvelle configuration publiée.')}
async function uploadApk(){const f=$('apkFile').files[0];if(!f){alert('Choisis un fichier APK.');return}const r=await fetch('/v1/admin/app-update/apk',{method:'PUT',headers:{'X-Admin-Token':TOKEN,'Content-Type':'application/vnd.android.package-archive'},body:f});let d={};try{d=await r.json()}catch{}if(!r.ok){alert(d.detail||('HTTP '+r.status));return}$('updUrl').value=d.apk_url;$('updateStatus').innerHTML='<span class="ok">APK téléversé • '+esc(Math.round(d.size_bytes/1024/1024*10)/10)+' Mo</span>';}
async function loadUpdate(){const u=await api('/v1/admin/app-update');$('updEnabled').checked=u.enabled;$('updMandatory').checked=u.mandatory;$('updCode').value=u.latest_version_code;$('updName').value=u.latest_version_name;$('updUrl').value=u.apk_url;$('updMessage').value=u.message;$('updateStatus').textContent='Dernière modification : '+u.updated_at}
async function saveUpdate(){const body={enabled:$('updEnabled').checked,mandatory:$('updMandatory').checked,latest_version_code:Number($('updCode').value||1),latest_version_name:$('updName').value.trim(),apk_url:$('updUrl').value.trim(),message:$('updMessage').value.trim()};try{const u=await api('/v1/admin/app-update',{method:'POST',body:JSON.stringify(body)});$('updateStatus').innerHTML='<span class="ok">Mise à jour enregistrée • '+esc(u.updated_at)+'</span>'}catch(e){$('updateStatus').innerHTML='<span class="bad">'+esc(e.message)+'</span>'}}
if(TOKEN){$('loginCard').classList.add('hidden');$('app').classList.remove('hidden');refreshAll().catch(()=>logout())}
</script>
</body></html>"""
