from __future__ import annotations

ADMIN_PANEL_HTML = r"""<!doctype html>
<html lang="fr">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Barka Tunnel Admin</title>
<style>
:root{--blue:#126ee8;--navy:#111827;--muted:#667085;--line:#dce3ee;--bg:#f6f8fc;--ok:#16a34a;--bad:#dc2626}
*{box-sizing:border-box}body{margin:0;font-family:system-ui,-apple-system,Segoe UI,sans-serif;background:var(--bg);color:var(--navy)}
header{background:linear-gradient(135deg,#0b63dc,#124cc4);color:white;padding:22px 18px;border-radius:0 0 26px 26px;box-shadow:0 8px 24px #0b63dc25}
header h1{margin:0;font-size:23px}header p{margin:5px 0 0;opacity:.85;font-size:13px}.wrap{max-width:980px;margin:auto;padding:16px}.card{background:white;border:1px solid var(--line);border-radius:18px;padding:16px;margin-bottom:14px;box-shadow:0 4px 18px #1018280b}.title{font-weight:800;font-size:17px;margin-bottom:12px;color:#0b60d1}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.stat{border:1px solid var(--line);border-radius:14px;padding:12px}.stat b{display:block;font-size:23px}.stat span{font-size:12px;color:var(--muted)}label{display:block;font-size:12px;font-weight:700;margin:10px 0 5px;color:#344054}input,select,textarea{width:100%;border:1px solid #cfd7e6;border-radius:12px;padding:12px;font:inherit;background:#fff;color:#111827}textarea{min-height:135px;font-family:ui-monospace,SFMono-Regular,monospace;font-size:12px}button{border:0;border-radius:12px;padding:12px 14px;background:var(--blue);color:white;font-weight:800;font-size:14px}button.secondary{background:#eef4ff;color:#0b60d1}button.danger{background:#fff1f2;color:#be123c;border:1px solid #fecdd3}.row{display:flex;gap:9px;align-items:center}.row>*{flex:1}.hidden{display:none!important}.status{font-size:13px;margin:8px 0;padding:10px;border-radius:11px;background:#f2f4f7}.ok{color:var(--ok)}.bad{color:var(--bad)}.code{font-family:ui-monospace,monospace;font-weight:800;letter-spacing:.4px}.code-row{border-top:1px solid #eef1f6;padding:10px 0}.small{font-size:11px;color:var(--muted)}.service{border:1px solid var(--line);border-radius:15px;padding:13px;margin:10px 0}.pill{font-size:11px;font-weight:800;background:#eef4ff;color:#0b60d1;border-radius:99px;padding:5px 8px;display:inline-block}.switch{display:flex;align-items:center;gap:8px}.switch input{width:auto}.toolbar{display:flex;gap:8px;flex-wrap:wrap}.toolbar button{flex:1;min-width:130px}@media(min-width:760px){.grid{grid-template-columns:repeat(4,1fr)}.services{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.service{margin:0}}
</style>
</head>
<body>
<header><h1>Barka Tunnel Admin</h1><p>Codes • Services VPN • Mises à jour</p></header>
<div class="wrap">
<section id="loginCard" class="card"><div class="title">Connexion administrateur</div><label>Mot de passe administrateur</label><input id="adminToken" type="password" autocomplete="current-password" placeholder="Mot de passe"><div style="height:10px"></div><button onclick="login()">OUVRIR LE PANEL</button><div id="loginStatus" class="status">Le mot de passe reste seulement dans cette session du navigateur.</div></section>
<div id="app" class="hidden">
<section class="card"><div class="row"><div><div class="title" style="margin:0">Tableau de bord</div><div class="small">Actualisation en temps réel</div></div><button class="secondary" onclick="refreshAll()">ACTUALISER</button></div><div id="stats" class="grid" style="margin-top:12px"></div></section>
<section class="card"><div class="title">Générer des codes</div><div class="row"><div><label>Offre</label><select id="plan"><option value="24h">24 heures — 300 XOF</option><option value="1w">1 semaine — 800 XOF</option><option value="2w">2 semaines — 1 000 XOF</option><option value="1m">1 mois — 2 000 XOF</option></select></div><div><label>Quantité</label><input id="count" type="number" min="1" max="100" value="1"></div></div><div style="height:10px"></div><button onclick="generateCodes()">GÉNÉRER</button><div id="generated"></div><div class="title" style="margin-top:18px">Derniers codes</div><div id="codes"></div></section>
<section class="card"><div class="title">Services VPN</div><div class="small">MOOV = SlowDNS • Orange = VLESS • Telecel = UDP. Le protocole de chaque opérateur est verrouillé côté serveur.</div><div id="services" class="services"></div></section>
<section class="card"><div class="title">Mise à jour de l'application</div><div class="row"><label class="switch"><input id="updEnabled" type="checkbox"> Activer</label><label class="switch"><input id="updMandatory" type="checkbox"> Obligatoire</label></div><div class="row"><div><label>Version code</label><input id="updCode" type="number" min="1"></div><div><label>Version affichée</label><input id="updName" placeholder="1.1.0"></div></div><label>Lien HTTPS de l'APK</label><input id="updUrl" placeholder="https://..."><label>Ou téléverser directement un APK</label><input id="apkFile" type="file" accept=".apk,application/vnd.android.package-archive"><div style="height:8px"></div><button class="secondary" onclick="uploadApk()">TÉLÉVERSER L'APK</button><label>Message</label><textarea id="updMessage" style="min-height:85px"></textarea><div style="height:10px"></div><button onclick="saveUpdate()">ENREGISTRER LA MISE À JOUR</button><div id="updateStatus" class="status"></div></section>
<section class="card"><div class="toolbar"><button class="secondary" onclick="logout()">SE DÉCONNECTER</button><button class="secondary" onclick="window.open('/docs','_blank')">API / DOCS</button></div></section>
</div></div>
<script>
let TOKEN=sessionStorage.getItem('barkaAdminToken')||'';
const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function api(path,opt={}){const headers={'Accept':'application/json','X-Admin-Token':TOKEN,...(opt.headers||{})};if(opt.body)headers['Content-Type']='application/json';const r=await fetch(path,{...opt,headers,cache:'no-store'});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.detail||('HTTP '+r.status));return data}
async function login(){TOKEN=$('adminToken').value.trim();if(!TOKEN)return;try{await api('/v1/admin/stats');sessionStorage.setItem('barkaAdminToken',TOKEN);$('loginCard').classList.add('hidden');$('app').classList.remove('hidden');await refreshAll()}catch(e){$('loginStatus').innerHTML='<span class="bad">'+esc(e.message)+'</span>';TOKEN=''}}
function logout(){sessionStorage.removeItem('barkaAdminToken');TOKEN='';location.reload()}
async function refreshAll(){try{await Promise.all([loadStats(),loadCodes(),loadServices(),loadUpdate()])}catch(e){if(String(e.message).includes('refusé'))logout();else alert(e.message)}}
async function loadStats(){const s=await api('/v1/admin/stats');const items=[['Appareils',s.devices],['Abonnements actifs',s.active_subscriptions],['Essais actifs',s.active_trials],['Codes disponibles',s.codes_issued],['Codes utilisés',s.codes_redeemed],['Paiements confirmés',s.payments_paid],['Paiements en attente',s.payments_pending],['Services actifs',s.vpn_services_enabled]];$('stats').innerHTML=items.map(x=>'<div class="stat"><b>'+esc(x[1])+'</b><span>'+esc(x[0])+'</span></div>').join('')}
async function generateCodes(){const d=await api('/v1/admin/codes',{method:'POST',body:JSON.stringify({plan_id:$('plan').value,count:Number($('count').value||1)})});$('generated').innerHTML='<div class="status ok">'+d.codes.map(c=>'<div class="code">'+esc(c)+' <button class="secondary" style="padding:6px" onclick="copyText(\''+c+'\')">COPIER</button></div>').join('')+'</div>';await loadCodes();await loadStats()}
async function copyText(t){await navigator.clipboard.writeText(t)}
async function loadCodes(){const list=await api('/v1/admin/codes?limit=60');$('codes').innerHTML=list.length?list.map(c=>'<div class="code-row"><div class="row"><div><div class="code">'+esc(c.code)+'</div><div class="small">'+esc(c.plan_id)+' • '+esc(c.source_type)+' • '+esc(c.status)+'</div></div>'+(c.status==='issued'?'<button class="danger" onclick="revokeCode(\''+c.code+'\')">DÉSACTIVER</button>':'')+'</div></div>').join(''):'<div class="status">Aucun code.</div>'}
async function revokeCode(code){if(!confirm('Désactiver ce code ?'))return;const d=await api('/v1/admin/codes/revoke',{method:'POST',body:JSON.stringify({code})});alert(d.message);await loadCodes();await loadStats()}
async function loadServices(){const list=await api('/v1/admin/vpn/profiles');$('services').innerHTML=list.map(p=>'<div class="service" data-id="'+esc(p.network_id)+'"><div class="row"><b>'+esc(p.display_name)+'</b><span class="pill">'+esc(p.protocol)+'</span></div><label class="switch"><input class="enabled" type="checkbox" '+(p.enabled?'checked':'')+'> Service actif</label><label>Priorité</label><input class="priority" type="number" min="1" max="1000" value="'+esc(p.priority)+'"><label>Configuration JSON</label><textarea class="config">'+esc(JSON.stringify(p.config,null,2))+'</textarea><div class="small">Version serveur : '+esc(p.version)+' • '+esc(p.updated_at)+'</div><div style="height:9px"></div><button onclick="saveService(\''+p.network_id+'\',\''+p.display_name+'\',\''+p.protocol+'\')">ENREGISTRER</button></div>').join('')}
async function saveService(id,name,protocol){const el=document.querySelector('.service[data-id="'+id+'"]');let config={};try{config=JSON.parse(el.querySelector('.config').value||'{}')}catch{alert('JSON invalide');return}const body={network_id:id,display_name:name,protocol,enabled:el.querySelector('.enabled').checked,priority:Number(el.querySelector('.priority').value||100),config};await api('/v1/admin/vpn/profiles',{method:'POST',body:JSON.stringify(body)});await loadServices();await loadStats();alert('Service enregistré.')}
async function uploadApk(){const f=$('apkFile').files[0];if(!f){alert('Choisis un fichier APK.');return}const r=await fetch('/v1/admin/app-update/apk',{method:'PUT',headers:{'X-Admin-Token':TOKEN,'Content-Type':'application/vnd.android.package-archive'},body:f});let d={};try{d=await r.json()}catch{}if(!r.ok){alert(d.detail||('HTTP '+r.status));return}$('updUrl').value=d.apk_url;$('updateStatus').innerHTML='<span class="ok">APK téléversé • '+esc(Math.round(d.size_bytes/1024/1024*10)/10)+' Mo</span>';}
async function loadUpdate(){const u=await api('/v1/admin/app-update');$('updEnabled').checked=u.enabled;$('updMandatory').checked=u.mandatory;$('updCode').value=u.latest_version_code;$('updName').value=u.latest_version_name;$('updUrl').value=u.apk_url;$('updMessage').value=u.message;$('updateStatus').textContent='Dernière modification : '+u.updated_at}
async function saveUpdate(){const body={enabled:$('updEnabled').checked,mandatory:$('updMandatory').checked,latest_version_code:Number($('updCode').value||1),latest_version_name:$('updName').value.trim(),apk_url:$('updUrl').value.trim(),message:$('updMessage').value.trim()};try{const u=await api('/v1/admin/app-update',{method:'POST',body:JSON.stringify(body)});$('updateStatus').innerHTML='<span class="ok">Mise à jour enregistrée • '+esc(u.updated_at)+'</span>'}catch(e){$('updateStatus').innerHTML='<span class="bad">'+esc(e.message)+'</span>'}}
if(TOKEN){$('loginCard').classList.add('hidden');$('app').classList.remove('hidden');refreshAll().catch(()=>logout())}
</script>
</body></html>"""
