from __future__ import annotations


RESELLER_PANEL_HTML = r"""<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <meta name="theme-color" content="#0f172a">
  <title>Barka Tunnel — Revendeur</title>
  <style>
    :root{--blue:#126ee8;--blue2:#0b60d1;--navy:#0f172a;--navy2:#182235;--muted:#667085;--line:#e2e8f0;--bg:#f4f7fb;--surface:#fff;--bad:#dc2626;--ok:#16a34a;--warn:#d97706;--shadow:0 12px 35px rgba(15,23,42,.08)}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font-family:Inter,system-ui,-apple-system,Segoe UI,sans-serif;background:var(--bg);color:var(--navy)}button,input,select{font:inherit}.hidden{display:none!important}.mobile-only{display:none}.desktop-only{display:inline-flex}
    .login-page{min-height:100vh;display:grid;place-items:center;padding:24px;background:radial-gradient(circle at top right,#dbeafe 0,transparent 35%),linear-gradient(135deg,#f8fbff,#eef4ff)}.login-card{width:min(450px,100%);background:#fff;border:1px solid var(--line);border-radius:28px;padding:28px;box-shadow:0 24px 70px rgba(15,23,42,.12)}
    .brand-lockup{display:flex;align-items:center;gap:13px;margin-bottom:24px}.brand-mark{width:48px;height:48px;border-radius:16px;display:grid;place-items:center;background:#fff;box-shadow:0 10px 24px rgba(18,110,232,.18);border:1px solid #dbeafe;overflow:hidden}.brand-mark svg{width:88%;height:88%;display:block}.brand-lockup h1{font-size:21px;margin:0}.brand-lockup p{margin:3px 0 0;color:var(--muted);font-size:13px}
    .app-shell{min-height:100vh;display:grid;grid-template-columns:255px minmax(0,1fr)}.sidebar{position:sticky;top:0;height:100vh;background:linear-gradient(180deg,#0d1729,#111d31);color:#fff;padding:18px 14px;display:flex;flex-direction:column;z-index:30}.side-brand{display:flex;align-items:center;gap:11px;padding:8px 8px 20px;border-bottom:1px solid rgba(255,255,255,.08);margin-bottom:14px}.side-brand .brand-mark{width:40px;height:40px;border-radius:13px}.side-brand strong{display:block}.side-brand span{display:block;color:#9fb0c9;font-size:11px;margin-top:2px}.nav-label{color:#72839f;font-size:10px;font-weight:800;letter-spacing:.12em;padding:11px 10px 7px;text-transform:uppercase}.nav{display:grid;gap:5px}.nav button{width:100%;display:flex;align-items:center;gap:11px;border:0;background:transparent;color:#b9c5d7;padding:11px 12px;border-radius:12px;text-align:left;font-weight:750;cursor:pointer}.nav button:hover{background:rgba(255,255,255,.07);color:#fff}.nav button.active{background:linear-gradient(90deg,rgba(18,110,232,.28),rgba(18,110,232,.12));color:#fff;box-shadow:inset 3px 0 0 #4da0ff}.nav-icon{width:24px;text-align:center;font-size:16px}.side-footer{margin-top:auto;padding:12px 8px;border-top:1px solid rgba(255,255,255,.08)}.side-footer .small{color:#7f91ac}
    .main{min-width:0}.topbar{height:72px;position:sticky;top:0;z-index:20;background:rgba(244,247,251,.92);backdrop-filter:blur(16px);border-bottom:1px solid rgba(226,232,240,.85);display:flex;align-items:center;justify-content:space-between;padding:0 28px;gap:12px}.topbar-main{display:flex;align-items:center;gap:10px;min-width:0;flex:1}.topbar-copy{min-width:0}.topbar h2{font-size:19px;margin:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.topbar p{font-size:12px;color:var(--muted);margin:2px 0 0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.top-actions{display:flex;align-items:center;gap:8px;flex:0 0 auto}.content{padding:24px 28px 40px;max-width:1440px;margin:auto}.page{display:none}.page.active{display:block}.page-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;margin-bottom:18px}.page-head h1{font-size:25px;margin:0 0 5px}.page-head p{color:var(--muted);margin:0;font-size:13px}
    .card{background:var(--surface);border:1px solid var(--line);border-radius:20px;padding:20px;margin-bottom:18px;box-shadow:var(--shadow)}.title{font-weight:850;font-size:18px;margin-bottom:12px;color:var(--blue2)}.small{font-size:11px;color:var(--muted)}.section-note{color:var(--muted);font-size:12px;margin:-5px 0 14px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.stat{border:1px solid var(--line);border-radius:17px;padding:16px;background:#fbfdff;min-width:0}.stat b{display:block;font-size:26px;line-height:1;color:var(--navy);margin-bottom:8px}.stat span{font-size:12px;color:var(--muted);font-weight:700}.stat.expired-stat{background:#fff1f2;border-color:#fecdd3}.stat.expired-stat b,.stat.expired-stat span{color:#b91c1c}.two-col{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(280px,.75fr);gap:18px}.quick-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.quick{border:1px solid var(--line);border-radius:16px;padding:15px;background:#fbfdff}.quick b{display:block;margin-bottom:4px}.quick span{display:block;font-size:12px;color:var(--muted);min-height:34px}.quick button{margin-top:12px;width:100%}
    label{display:block;font-size:12px;font-weight:750;margin:10px 0 6px;color:#344054}input,select{width:100%;border:1px solid #cfd7e6;border-radius:12px;padding:11px 12px;background:#fff;color:#111827;outline:none;transition:.18s}input:focus,select:focus{border-color:#69a7f5;box-shadow:0 0 0 4px rgba(18,110,232,.09)}button{border:0;border-radius:12px;padding:11px 14px;background:var(--blue);color:#fff;font-weight:800;font-size:13px;cursor:pointer;transition:.18s}button:hover{filter:brightness(.98);transform:translateY(-1px)}button.secondary{background:#eef4ff;color:#0b60d1}button.ghost{background:#fff;color:#344054;border:1px solid var(--line)}button.danger{background:#fff1f2;color:#be123c;border:1px solid #fecdd3}.icon-btn{width:40px;height:40px;padding:0;display:grid;place-items:center}.row{display:flex;gap:10px;align-items:center}.row>*{flex:1}.status{font-size:13px;margin:10px 0;padding:11px 12px;border-radius:12px;background:#f2f4f7}.ok{color:var(--ok)}.bad{color:var(--bad)}.result{margin-top:14px;padding:14px;border:1px solid #86efac;background:#f0fdf4;border-radius:14px}.code{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-weight:850;letter-spacing:.3px;overflow-wrap:anywhere}.code-row{border-top:1px solid #eef1f6;padding:11px 0}.code-row.expired{background:#fff1f2;border:1px solid #fecdd3;border-radius:14px;margin:8px 0;padding:11px}.expired-label{color:#b91c1c;font-weight:900}.code-actions{display:flex;gap:7px;justify-content:flex-end;flex:0 0 auto}.code-actions button{flex:0 0 auto;padding:8px 10px}.filterbar{display:flex;gap:10px;align-items:center;margin:12px 0}.filterbar input{flex:1}.filterbar select{max-width:200px}.account-card{display:flex;align-items:center;justify-content:space-between;gap:18px}.account-name{font-size:21px;font-weight:850}.account-expiry{background:#eef4ff;color:#0b60d1;border-radius:14px;padding:12px 14px;text-align:right}.account-expiry b{display:block;font-size:13px}.account-expiry span{font-size:12px}.overlay{display:none}
    @media(max-width:980px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}.quick-grid{grid-template-columns:1fr}.two-col{grid-template-columns:1fr}}
    @media(max-width:760px){.mobile-only{display:grid}.desktop-only{display:none!important}.app-shell{display:block}.sidebar{position:fixed;left:0;top:0;width:min(285px,86vw);transform:translateX(-105%);transition:transform .22s ease}.app-shell.menu-open .sidebar{transform:translateX(0)}.overlay{display:block;position:fixed;inset:0;background:rgba(15,23,42,.46);z-index:25;opacity:0;pointer-events:none;transition:opacity .22s}.app-shell.menu-open .overlay{opacity:1;pointer-events:auto}.topbar{padding:0 14px;height:66px}.content{padding:18px 14px 34px}.page-head h1{font-size:22px}.account-card{align-items:flex-start;flex-direction:column}.account-expiry{width:100%;text-align:left}.row.mobile-stack{align-items:flex-start;flex-direction:column}.row.mobile-stack>*{width:100%}.code-actions{width:100%;justify-content:flex-end}.filterbar{align-items:stretch;flex-direction:column}.filterbar select{max-width:none}.top-actions .ghost{display:none}.login-page{padding:max(18px,env(safe-area-inset-top)) 14px max(18px,env(safe-area-inset-bottom))}.login-card{padding:22px}.content{padding-bottom:max(34px,env(safe-area-inset-bottom))}}
    @media(max-width:430px){.grid{grid-template-columns:1fr 1fr}.stat{padding:14px}.stat b{font-size:23px}.page-head{display:block}.card{padding:16px;border-radius:18px}.code-actions button{width:100%}}
  .code-row.in-use{background:#f0fdf4;border:1px solid #bbf7d0;border-radius:14px;margin:8px 0;padding:11px}.code-row.in-use .code,.code-row.in-use .small{color:#166534}.code-row.expired .code,.code-row.expired .small{color:#b91c1c}.code-actions{flex-wrap:wrap}.credentials-grid{display:grid;gap:10px}.credential-line{display:flex;gap:12px;align-items:center;justify-content:space-between;padding:12px;background:white;border-radius:12px}.credential-line>div{min-width:0;overflow-wrap:anywhere}.credential-line button{flex-shrink:0}.audit-line{border-top:1px solid var(--line);padding:10px 0;overflow-wrap:anywhere}.bulk-action{margin-bottom:12px}
</style>
</head>
<body>
  <section id="loginCard" class="login-page">
    <div class="login-card">
      <div class="brand-lockup"><div class="brand-mark"><svg viewBox="0 0 72 72" role="img" aria-label="Logo Barka Tunnel"><path d="M62 9C47 0 24 2 11 16C-1 29 1 50 15 62C29 74 51 70 63 56" fill="none" stroke="#126ee8" stroke-width="5" stroke-linecap="round"/><path d="M22 16V58M22 16H40C51 16 57 22 57 30C57 36 52 40 47 41C54 42 59 47 59 54C59 63 51 67 40 67H22" fill="none" stroke="#111827" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div><h1>Barka Tunnel</h1><p>Sous-panel revendeur sécurisé</p></div></div>
      <div class="title">Connexion revendeur</div><div class="section-note">Utilisez les coordonnées remises par l'administrateur.</div>
      <label>Nom d'utilisateur</label><input id="username" autocomplete="username" maxlength="200">
      <label>Mot de passe</label><input id="password" type="password" autocomplete="current-password" maxlength="200">
      <div style="height:14px"></div><button style="width:100%" onclick="login()">SE CONNECTER</button><div id="loginStatus"></div>
    </div>
  </section>

  <div id="app" class="app-shell hidden">
    <aside class="sidebar">
      <div class="side-brand"><div class="brand-mark"><svg viewBox="0 0 72 72" role="img" aria-label="Logo Barka Tunnel"><path d="M62 9C47 0 24 2 11 16C-1 29 1 50 15 62C29 74 51 70 63 56" fill="none" stroke="#126ee8" stroke-width="5" stroke-linecap="round"/><path d="M22 16V58M22 16H40C51 16 57 22 57 30C57 36 52 40 47 41C54 42 59 47 59 54C59 63 51 67 40 67H22" fill="none" stroke="#111827" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div><strong>Barka Tunnel</strong><span>Panel revendeur</span></div></div>
      <div class="nav-label">Navigation</div>
      <nav class="nav">
        <button class="active" data-page="dashboard" onclick="showPage('dashboard',this)"><span class="nav-icon">⌂</span>Tableau de bord</button>
        <button data-page="subscription" onclick="showPage('subscription',this)"><span class="nav-icon">¤</span>Abonnement</button>
        <button data-page="test" onclick="showPage('test',this)"><span class="nav-icon">◷</span>Test 2 h</button>
        <button data-page="codes" onclick="showPage('codes',this)"><span class="nav-icon"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false" style="display:block;margin:auto"><path d="M3 8h18v4H3zM5 12v9h14v-9M12 8v13M12 8H7.5A2.5 2.5 0 1 1 10 5.5L12 8Zm0 0h4.5A2.5 2.5 0 1 0 14 5.5L12 8Z"/></svg></span>Mes codes</button>
      </nav>
      <div class="nav-label">Compte</div>
      <nav class="nav"><button onclick="refreshAll()"><span class="nav-icon">↻</span>Actualiser les données</button></nav>
      <div class="side-footer"><button class="ghost" style="width:100%" onclick="logout()">Se déconnecter</button><div class="small" style="margin-top:10px;text-align:center">Permissions revendeur limitées</div></div>
    </aside>
    <div class="overlay" onclick="toggleMenu(false)"></div>

    <main class="main">
      <header class="topbar"><div class="topbar-main"><button class="icon-btn secondary mobile-only" onclick="toggleMenu()" aria-label="Ouvrir le menu">☰</button><div class="topbar-copy"><h2 id="topTitle">Tableau de bord</h2><p id="topSubtitle">Vue générale de votre activité</p></div></div><div class="top-actions"><button class="icon-btn ghost" onclick="refreshAll()" aria-label="Actualiser">↻</button><button class="ghost desktop-only" onclick="logout()">SE DÉCONNECTER</button></div></header>
      <div class="content">
        <section class="page active" data-page="dashboard">
          <div class="page-head"><div><h1>Tableau de bord</h1><p>Suivez vos codes et accédez rapidement à vos outils autorisés.</p></div></div>
          <section class="card account-card"><div><div class="small">COMPTE REVENDEUR</div><div class="account-name" id="accountName">—</div><div class="small">Compte actif et limité à la génération de codes d'abonnement et de tests 2 h.</div></div><div class="account-expiry"><b>EXPIRATION DU SOUS-PANEL</b><span id="accountExpiry">—</span></div></section>
          <div id="stats" class="grid"><div class="stat"><b>—</b><span>Chargement…</span></div></div>
          <div style="height:18px"></div>
          <section class="card"><div class="title">Actions rapides</div><div class="quick-grid"><div class="quick"><b>Nouvel abonnement</b><span>Créer un code individuel selon la durée choisie.</span><button onclick="showPage('subscription')">GÉNÉRER</button></div><div class="quick"><b>Nouveau test</b><span>Créer un test individuel limité exactement à 2 heures.</span><button onclick="showPage('test')">TEST 2 H</button></div><div class="quick"><b>Consulter mes codes</b><span>Rechercher, filtrer et supprimer uniquement vos propres codes.</span><button class="secondary" onclick="showPage('codes')">VOIR MES CODES</button></div></div></section>
          <section class="card"><button class="danger" onclick="resetStats()">RÉINITIALISER LES STATISTIQUES</button><div id="statsResetInfo" class="small"></div></section>
          <section class="card"><div class="row mobile-stack"><div><div class="title" style="margin:0">Codes récents</div><div class="small">Vos cinq dernières créations.</div></div><button class="ghost" onclick="showPage('codes')">TOUT AFFICHER</button></div><div id="recentCodes"><div class="status">Chargement…</div></div></section>
        </section>

        <section class="page" data-page="subscription">
          <div class="page-head"><div><h1>Générer un abonnement</h1><p>Un code individuel utilisable par un seul utilisateur.</p></div></div>
          <div class="two-col"><section class="card"><div class="title">Code d'abonnement</div><label>Durée</label><select id="plan"><option value="24h">24 HEURES</option><option value="1w">1 SEMAINE</option><option value="2w">2 SEMAINES</option><option value="1m">1 MOIS</option></select><div style="height:12px"></div><button onclick="generateSubscription()">GÉNÉRER LE CODE</button><div id="subscriptionResult" class="hidden"></div></section><section class="card"><div class="title">Autorisation</div><div class="status">Cette page crée uniquement un abonnement individuel parmi les quatre durées autorisées. Aucun autre réglage n'est accessible.</div></section></div>
        </section>

        <section class="page" data-page="test">
          <div class="page-head"><div><h1>Générer un test 2 h</h1><p>Un code d'essai individuel limité exactement à deux heures.</p></div></div>
          <div class="two-col"><section class="card"><div class="title">Test individuel</div><div class="status">Durée fixe : <b>2 heures</b><br>Utilisation : <b>un seul utilisateur</b></div><button onclick="generateTest()">GÉNÉRER LE TEST 2 H</button><div id="testResult" class="hidden"></div></section><section class="card"><div class="title">Autorisation</div><div class="status">La durée du test est verrouillée à 2 heures. Le revendeur ne peut ni la modifier ni accéder aux réglages administrateur.</div></section></div>
        </section>

        <section class="page" data-page="codes">
          <div class="page-head"><div><h1>Mes codes</h1><p>Uniquement les codes générés depuis votre propre sous-panel.</p></div></div>
          <section class="card"><div class="row mobile-stack"><div><div class="title" style="margin:0">Liste des codes</div><div class="small">Les codes arrivés à zéro apparaissent entièrement en rouge avec le statut EXPIRÉ.</div></div><button class="ghost" onclick="loadCodesAndStats()">ACTUALISER</button></div><div class="filterbar"><input id="codeSearch" placeholder="Rechercher un code, une durée ou un statut…" oninput="renderCodes()"><select id="codeStatus" onchange="renderCodes()"><option value="">Tous les statuts</option><option value="issued">Disponibles</option><option value="redeemed">Actifs / utilisés</option><option value="expired">Expirés</option><option value="revoked">Désactivés</option></select></div><button id="codeDeleteFiltered" class="danger bulk-action hidden" onclick="deleteFiltered('subscription')">SUPPRIMER TOUS LES RÉSULTATS DU FILTRE</button><div id="codeCount" class="small"></div><div id="codes"><div class="status">Chargement…</div></div></section>
        </section>
      </div>
    </main>
  </div>

<script>
const IS_RESELLER=true;

async function loadAllCodes(path){let rows=[];for(let offset=0;;offset+=200){const page=await api(path+'?limit=200&offset='+offset);rows.push(...page);if(page.length<200)return rows}}
function codeMatches(c,q,st,redeem=false){return (!st||c.status===st)&&(!q||(redeem?[c.code,c.status]:[c.code,c.plan_id,planLabel(c.plan_id),c.status,statusLabel(c.status),c.code_type]).some(v=>String(v||'').toLowerCase().includes(q)))}
let bulkBusy=false;
async function deleteFiltered(kind){if(bulkBusy)return;const prefix=IS_RESELLER?'code':kind==='redeem'?'code':'subscription';const selected=$(prefix+'Status').value;if(!selected){alert('Choisissez un statut avant de supprimer les résultats du filtre.');return}const body={kind,status:selected,query:$(prefix+'Search').value.trim()};const base='/v1/reseller/codes';bulkBusy=true;try{const preview=await api(base+'/filter-preview',{method:'POST',body:JSON.stringify(body)});if(!preview.count){alert('Aucun code correspondant à supprimer.');return}if(!confirm('Supprimer les '+preview.count+' codes du filtre « '+statusLabel(selected)+' »'+(body.query?' (recherche : '+body.query+')':'')+' ? Le temps restant associé sera retiré. Les autres codes seront conservés.'))return;const result=await api(base+'/delete-filtered',{method:'POST',body:JSON.stringify({...body,fingerprint:preview.fingerprint})});alert(result.message);if(IS_RESELLER){['subscriptionResult','testResult'].forEach(id=>{$(id).classList.add('hidden');$(id).dataset.code=''});await loadCodesAndStats()}else{$('subscriptionGenerated').textContent='';$('generated').textContent='';await loadCodes();await loadStats()}}catch(e){alert(e.message)}finally{bulkBusy=false}}

const $=id=>document.getElementById(id);
let TOKEN=sessionStorage.getItem('barka_reseller_token')||'';
let latestCodes=[];
const pageMeta={dashboard:['Tableau de bord','Vue générale de votre activité'],subscription:['Abonnement','Générer un code individuel'],test:['Test 2 h','Générer un essai individuel'],codes:['Mes codes','Rechercher et gérer vos créations']};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const formatDate=v=>{if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('fr-FR')};
const planLabel=v=>v==='24h'?'24 HEURES':v==='1w'?'1 SEMAINE':v==='2w'?'2 SEMAINES':v==='1m'?'1 MOIS':v==='test_2h'?'TEST 2 H':v;
const statusLabel=v=>v==='issued'?'Disponible':v==='redeemed'?'Actif / utilisé':v==='expired'?'EXPIRÉ':v==='revoked'?'Désactivé':v;
async function api(path,opt={}){const headers={'Accept':'application/json',...(opt.headers||{})};if(TOKEN)headers.Authorization='Bearer '+TOKEN;if(opt.body)headers['Content-Type']='application/json';const r=await fetch(path,{...opt,headers,cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok){const e=new Error(d.detail||('Erreur HTTP '+r.status));e.status=r.status;throw e}return d}
function toggleMenu(force){const app=$('app');if(!app)return;const next=typeof force==='boolean'?force:!app.classList.contains('menu-open');app.classList.toggle('menu-open',next)}
function showPage(name,btn){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===name));document.querySelectorAll('.nav button[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===name));const meta=pageMeta[name]||pageMeta.dashboard;$('topTitle').textContent=meta[0];$('topSubtitle').textContent=meta[1];toggleMenu(false);window.scrollTo({top:0,behavior:'smooth'})}
function showLoggedIn(on){$('loginCard').classList.toggle('hidden',on);$('app').classList.toggle('hidden',!on)}
async function login(){const username=$('username').value.trim(),password=$('password').value;$('loginStatus').innerHTML='<div class="status">Connexion…</div>';try{const d=await api('/v1/reseller/login',{method:'POST',body:JSON.stringify({username,password})});TOKEN=d.token;sessionStorage.setItem('barka_reseller_token',TOKEN);$('password').value='';$('loginStatus').innerHTML='';showLoggedIn(true);await refreshAll()}catch(e){$('loginStatus').innerHTML='<div class="status bad">'+esc(e.message)+'</div>'}}
async function logout(){try{if(TOKEN)await api('/v1/reseller/logout',{method:'POST'})}catch{}TOKEN='';sessionStorage.removeItem('barka_reseller_token');showLoggedIn(false);toggleMenu(false)}
async function refreshAll(){try{const results=await Promise.all([api('/v1/reseller/account'),api('/v1/reseller/stats'),loadAllCodes('/v1/reseller/codes')]);renderAccount(results[0]);renderStats(results[1]);latestCodes=results[2];renderCodes();renderRecentCodes()}catch(e){if(e.status===401){await logout();$('loginStatus').innerHTML='<div class="status bad">'+esc(e.message)+'</div>'}else alert(e.message)}}
function renderAccount(account){$('accountName').textContent=account.username;$('accountExpiry').textContent=formatDate(account.expires_at)}
async function resetStats(){const confirmation=prompt('Réinitialiser uniquement vos compteurs ? Vos codes, abonnements et journaux sont conservés. Tapez exactement oui pour valider.');if(confirmation===null)return;if(confirmation!=='oui'){alert('Confirmation incorrecte. Aucune modification.');return}try{const d=await api('/v1/reseller/stats/reset',{method:'POST',body:JSON.stringify({confirmation})});await loadCodesAndStats();alert(d.message)}catch(e){alert(e.message)}}
function renderStats(stats){$('statsResetInfo').textContent=stats.stats_reset_at?'Compteurs depuis le '+formatDate(stats.stats_reset_at)+'. Vos codes et leur historique sont conservés.':'Historique complet.';const items=[['Total des codes',stats.total],['Codes disponibles',stats.available],['Actifs / utilisés',stats.active],['Codes expirés',stats.expired]];$('stats').innerHTML=items.map((item,index)=>'<div class="stat '+(index===3?'expired-stat':'')+'"><b>'+esc(item[1])+'</b><span>'+esc(item[0])+'</span></div>').join('')}
function codeRow(c){const expired=c.status==='expired';return '<div class="code-row '+(expired?'expired':c.status==='redeemed'?'in-use':'')+'"><div class="row mobile-stack"><div><div class="code">'+esc(c.code)+'</div><div class="small">'+esc(planLabel(c.plan_id))+' • <span class="'+(expired?'expired-label':'')+'">'+esc(statusLabel(c.status))+'</span></div><div class="small">Créé : '+formatDate(c.created_at)+' • Expire : '+formatDate(c.expires_at)+'</div></div><div class="code-actions"><button class="danger" onclick="deleteCode(\''+c.code+'\')">SUPPRIMER</button></div></div></div>'}
function renderRecentCodes(){$('recentCodes').innerHTML=latestCodes.length?latestCodes.slice(0,5).map(codeRow).join(''):'<div class="status">Aucun code généré.</div>'}
function renderCodes(){const q=($('codeSearch')?.value||'').trim().toLowerCase();const selected=$('codeStatus')?.value||'';$('codeDeleteFiltered').classList.toggle('hidden',!selected);const list=latestCodes.filter(c=>codeMatches(c,q,selected));$('codeCount').textContent=list.length+' code'+(list.length>1?'s':'')+' affiché'+(list.length>1?'s':'');$('codes').innerHTML=list.length?list.map(codeRow).join(''):'<div class="status">Aucun code correspondant.</div>'}
async function loadCodesAndStats(){try{const results=await Promise.all([loadAllCodes('/v1/reseller/codes'),api('/v1/reseller/stats')]);latestCodes=results[0];renderCodes();renderRecentCodes();renderStats(results[1])}catch(e){if(e.status===401){await logout();$('loginStatus').innerHTML='<div class="status bad">'+esc(e.message)+'</div>'}else alert(e.message)}}
function showResult(targetId,label,code){const target=$(targetId);target.classList.remove('hidden');target.className='result';target.dataset.code=code;target.innerHTML='<div class="title">'+esc(label)+'</div><div class="code">'+esc(code)+'</div><div style="height:9px"></div><button class="secondary" onclick="copyText(\''+code+'\')">COPIER LE CODE</button>'}
async function copyText(text){try{await navigator.clipboard.writeText(text)}catch{const t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}}
async function generateSubscription(){try{const d=await api('/v1/reseller/codes/subscription',{method:'POST',body:JSON.stringify({plan_id:$('plan').value})});showResult('subscriptionResult','Code d’abonnement créé',d.code);await loadCodesAndStats()}catch(e){alert(e.message)}}
async function generateTest(){try{const d=await api('/v1/reseller/codes/test',{method:'POST'});showResult('testResult','Test de 2 heures créé',d.code);await loadCodesAndStats()}catch(e){alert(e.message)}}
async function deleteCode(code){if(!confirm('Supprimer ce code ? S’il est déjà utilisé, son temps restant sera retiré.'))return;try{const d=await api('/v1/reseller/codes/delete',{method:'POST',body:JSON.stringify({code})});if(!d.success)throw new Error(d.message);['subscriptionResult','testResult'].forEach(id=>{const el=$(id);if((el.dataset.code||'')===code){el.classList.add('hidden');el.dataset.code=''}});await loadCodesAndStats()}catch(e){alert(e.message)}}
async function restore(){if(!TOKEN)return;showLoggedIn(true);await refreshAll()}
setInterval(()=>{if(TOKEN)loadCodesAndStats().catch(()=>{})},60000);
restore();
</script>
</body>
</html>"""
